### ISSUE TITLE
Implement font Passata (compatible with Futura)

### ISSUE THREAD

**Issue by ronaldtse** [fontist/formulas#59]
Implement font Passata (compatible with Futura):

- Futura => Passata (https://medarbejdere.au.dk/en/administration/communication/guidelines/guidelinesforfonts/downloadfonts/) (Wikipedia: Passata is a modernized version of Futura)

_Originally posted by @ronaldtse in https://github.com/fontist/fontist/issues/126#issuecomment-736980262_

**Comment by ronaldtse** [comment]
According to https://medarbejdere.au.dk/en/administration/communication/guidelines/guidelinesforfonts/ , "Passata requires *no licences*".

<img width="492" alt="Screen Shot 2020-12-21 at 9 57 03 AM" src="https://user-images.githubusercontent.com/11865/102731464-e1e2c500-4372-11eb-971c-f68b5dec355f.png">

**Comment by ronaldtse** [comment]
Let's also add the other weights of Passata:
Passata Peto: https://medarbejdere.au.dk/fileadmin/www.designmanual.au.dk/hent_filer/hent_skrifttyper/AUPass_Peto.zip

Passata obliques: https://medarbejdere.au.dk/fileadmin/www.designmanual.au.dk/hent_filer/hent_skrifttyper/AUPass_Obliques.zip

Passata Light bold: https://medarbejdere.au.dk/en/administration/communication/guidelines/guidelinesforfonts/downloadfonts/fileadmin/www.designmanual.au.dk/hent_filer/hent_skrifttyper/AUPassLight_Bold.zip

**Comment by alexeymorozov** [comment]
There are styles of a font from different sources: the "AU Passata Light" font has the "Regular" style from the main archive, and the "Bold" style from the link above.

Currently there is no API for installation of a style from a different formula. I see the following choices:

1. Use separate formulas, and when searching for a proper formula choose it also by style. Now it's much easier since the searching mechanism is much simpler than before.
2. Implement several "required" sources for the same formula, and when installing download all of them.

Will try to implement the first one.

**Comment by alexeymorozov** [comment]
Extracted additional styles to #71.

Closing this.
