### ISSUE TITLE
Add WorkSans (non-variable) from original repo

### ISSUE THREAD

**Issue by ronaldtse** [fontist/formulas#7]
Seems that Google Fonts only provides the "variable size" font, but in some cases we need the static font weights.

We want to add the font from this repo:
https://github.com/weiweihuanghuang/Work-Sans

**Comment by Intelligent2013** [comment]
In https://github.com/fontist/formulas/blob/692f367c4ce90724dcfcdff15e34ab7f0c31df37/Formulas/google/work_sans.yml via url https://fonts.google.com/download?family=Work%20Sans Google provides a zip that contains static fonts (in `static` sub-folder).

**Comment by alexeymorozov** [comment]
Indeed, Google fonts include static fonts in a separate directory. They were missed because they are not listed in `METADATA.pb`.

An original repo contains a newer version of font v2.010 (vs v2.009 from Google), so I've created a formula from the repo.

Other thing to consider is that an archive from the original repo has a size of 115 MB vs 5 MB from Google.
